name: Build and Push Frontend Docker Image

on:
  push:
    branches: [main]
    paths:
      - "src/**"
      - "package.json"
      - "next.config.*"
      - "Dockerfile"
      - ".github/workflows/frontend-build.yml"

env:
  REGISTRY: docker.io
  IMAGE_NAME: mip92/tattoo-client

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Generate GraphQL types
        run: |
          export NEXT_PUBLIC_SERVER_URL=${{ secrets.GRAPHQL_SERVER_URL }}
          npm run codegen

      - name: Build Next.js application
        run: npm run build:docker

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Success message
        run: echo "Frontend Docker image successfully built and pushed to Docker Hub!"

  deploy-to-nginx:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Checkout tattoo-nginx repository
        uses: actions/checkout@v4
        with:
          repository: mip92/tattoo
          token: ${{ secrets.PAT_TOKEN }}
          path: tattoo-nginx

      - name: Check for changes
        id: check-changes
        run: |
          cd tattoo-nginx
          if git diff --quiet HEAD~1 HEAD; then
            echo "no_changes=true" >> $GITHUB_OUTPUT
            echo "No changes detected, skipping deployment"
          else
            echo "no_changes=false" >> $GITHUB_OUTPUT
            echo "Changes detected, proceeding with deployment"
          fi

      - name: Trigger deployment action
        if: steps.check-changes.outputs.no_changes == 'false'
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: mip92/tattoo-nginx
          event-type: deploy-frontend
          client-payload: '{"frontend_image": "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"}'
