name: Build and Push Frontend Docker Image

on:
  push:
    branches: [main]
    paths:
      - "src/**"
      - "package.json"
      - "next.config.*"
      - "Dockerfile"
      - ".github/workflows/frontend-build.yml"

env:
  REGISTRY: docker.io
  IMAGE_NAME: mip92/tattoo-client

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Generate GraphQL types
        run: |
          export NEXT_PUBLIC_SERVER_URL=${{ secrets.GRAPHQL_SERVER_URL }}
          npm run codegen

      - name: Build Next.js application
        run: npm run build:docker

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Success message
        run: echo "Frontend Docker image successfully built and pushed to Docker Hub!"

  deploy-to-nginx:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Checkout tattoo repository
        uses: actions/checkout@v4
        with:
          repository: mip92/tattoo
          token: ${{ secrets.PAT_TOKEN }}
          path: tattoo
          fetch-depth: 2

      - name: Check for changes
        id: check-changes
        run: |
          cd tattoo
          if git diff --quiet HEAD~1 HEAD; then
            echo "no_changes=true" >> $GITHUB_OUTPUT
            echo "No changes detected, skipping deployment"
          else
            echo "no_changes=false" >> $GITHUB_OUTPUT
            echo "Changes detected, proceeding with deployment"
          fi

      - name: Debug repository dispatch
        if: steps.check-changes.outputs.no_changes == 'false'
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          echo "🔍 Debug info:"
          echo "Repository: mip92/tattoo"
          echo "Event type: deploy-frontend"
          echo "Token exists: $([[ -n "$PAT_TOKEN" ]] && echo true || echo false)"
          echo "Token length: ${#PAT_TOKEN}"
          echo "Token preview: ${PAT_TOKEN:0:10}..."

      - name: Test API access
        if: steps.check-changes.outputs.no_changes == 'false'
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          echo "🧪 Testing API access to tattoo repository..."
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: token $PAT_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/mip92/tattoo")
          echo "API Response Code: $RESPONSE"
          if [ "$RESPONSE" = "200" ]; then
            echo "✅ API access successful"
          else
            echo "❌ API access failed with code: $RESPONSE"
          fi

      - name: Trigger deployment action
        if: steps.check-changes.outputs.no_changes == 'false'
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: mip92/tattoo
          event-type: deploy-frontend
          client-payload: '{"frontend_image": "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"}'
